[package]
name = "kime"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
ahash = "0.6.2"
cairo-rs = { version = "0.9.1", features = ["xcb"] }
log = "0.4.11"
num-derive = "0.3.3"
num-traits = "0.2.14"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_yaml = "0.8.15"
x11rb = { version = "0.7.0", features = ["render"] }
# xim = { git = "https://github.com/Riey/xim-rs", default-features = false, features = ["x11rb-server"] }
xim = { path = "../xim-rs", default-features = false, features = ["x11rb-server", "x11rb-xcb"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
