[package]
name = "kime"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
cstr = "0.2.8"
log = "0.4.11"
mio = { version = "0.7.6", features = ["os-ext", "os-poll", "os-util"] }
pretty_env_logger = "0.4.0"
x11rb = "0.7.0"
xkb = "0.2.1"
