[package]
name = "kime"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
log = "0.4.11"
pretty_env_logger = "0.4.0"
x11rb = { version = "0.7.0" }
# xim = { git = "https://github.com/Riey/xim-rs", default-features = false, features = ["x11rb-server"] }
xim = { path = "../xim-rs", default-features = false, features = ["x11rb-server"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
