[package]
name = "kime"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
ahash = "0.6.2"
anyhow = "1.0.36"
cstr = "0.2.8"
log = "0.4.11"
pretty_env_logger = "0.4.0"
static_assertions = "1.1.0"
x11rb = "0.7.0"
xim = { git = "https://github.com/Riey/xim-rs", default-features = false, features = ["x11rb-server"] }
