[package]
name = "kime-xtask"
version = "0.8.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[dependencies]
kime-engine-core = { path = "../engine/core" }
serde_yaml = "0.8.15"
structopt = "0.3.21"
strum = "0.20.0"
strum_macros = "0.20.1"
tempfile = "3.2.0"
