version: 2.1

jobs:
  markdown-lint:
    docker:
      - image: cimg/node:current
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: sudo npm install -g markdownlint-cli
      - run: sudo npm install -g markdown-link-check
      - run: .circleci/check_md.sh
  check:
    docker:
      - image: riey/kime-build:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ .Environment.CARGO_CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
            - cargo-{{ .Environment.CARGO_CACHE_VERSION }}-
      - run: cargo fmt -- --check
      - run: cargo xtask build --mode Debug XIM WAYLAND GTK2 GTK3 GTK4 QT5 QT6
      - run: cargo xtask test
      - save_cache:
          paths:
            - ./target
            - ~/.cargo
          key: cargo-{{ .Environment.CARGO_CACHE_VERSION }}-{{ checksum "Cargo.lock" }}

  build-release:
    docker:
      - image: riey/kime-build:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: cargo xtask build --mode Release XIM WAYLAND GTK2 GTK3 GTK4 QT5 QT6
      - run: mkdir -p /tmp/artifacts
      - run: 7z a /tmp/artifacts/kime-$(git tag --sort=v:refname | tail -1).7z ./build/out/*
      - run: cargo xtask release-deb /tmp/artifacts 
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts

  release-github:
    docker:
      - image: cibuilds/github:0.10
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git tag --sort=v:refname | tail -1)
            ghr -draft -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts

workflows:
  ci:
    jobs:
      - check
      - markdown-lint
  cd:
    jobs:
      - build-release:
          filters:
            branches:
              only: /releases.+/
            tags:
              only: /v.+/
      - release-github:
          requires:
            - build-release
          filters:
            branches:
              only: /releases.+/
            tags:
              only: /v.+/