version: 2.1

jobs:
  markdown-lint:
    docker:
      - image: cimg/node:current
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run: sudo npm install -g markdownlint-cli
      - run: sudo npm install -g markdown-link-check
      - run: .circleci/check_md.sh
  check:
    docker:
      - image: riey/kime-build:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ .Environment.CARGO_CACHE_VERSION }}-{{ checksum "Cargo.lock" }}
            - cargo-{{ .Environment.CARGO_CACHE_VERSION }}-
      - run: cargo fmt -- --check
      - run: cargo xtask build --mode Debug XIM WAYLAND GTK2 GTK3 GTK4 QT5 QT6
      - run: cargo xtask test
      - when:
          condition:
            equal: [develop, << pipeline.git.branch >>]
          steps:
            - save_cache:
                paths:
                  - ./target
                  - ~/.cargo
                key: cargo-{{ .Environment.CARGO_CACHE_VERSION }}-{{ checksum "Cargo.lock" }}

  build-release:
    docker:
      - image: riey/kime-build:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: ~/release
    steps:
      - checkout
      - run: cargo xtask build --mode Release XIM WAYLAND GTK2 GTK3 GTK4 QT5 QT6
      - run: mkdir -pv ~/release/gh
      - run: echo $(git tag --sort=v:refname | tail -1) > ~/release/tag
      - run: 7z a ~/release/gh/kime-$(git tag --sort=v:refname | tail -1).7z ./build/out/*
      - run: cargo xtask release-deb ~/release/gh
      - persist_to_workspace:
          root: .
          paths:
            - .

  gh-release:
    docker:
      - image: cibuilds/github:0.13

    working_directory: ~/release

    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload Release
          command: |
            TAG=$(cat ./tag)
            ghr -draft -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${TAG} ./gh/

workflows:
  ci:
    jobs:
      - check
      - markdown-lint
  cd:
    jobs:
      - require-gh-release:
          filters:
            branches:
              only: /releases.+/
          type: approval
      - build-release:
          filters:
            branches:
              only: /releases.+/
          requires:
            - require-gh-release
      - gh-release:
          filters:
            branches:
              only: /releases.+/
          requires:
            - build-release
