[package]
name = "kime-engine-config-writer"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[dependencies]
kime-engine-core = { path = "../core" }
serde_yaml = "0.8.15"

