[package]
name = "kime-engine-cffi"
version = "0.4.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[dependencies]
kime-engine = { path = "../engine" }

[build-dependencies]
bindgen = "0.56.0"
