name: Release

on:
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  packaging:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt-get update -y
      - name: Install packages
        run: sudo apt-get install -y pkg-config libpango1.0-dev libcairo2-dev libgtk-3-dev libglib2.0 libxcb1
      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Generate package...
        run: pkg/release.sh
      - name: Archiving package...
        run: 7z a kime.7z ./build/out/*
      - name: Generate deb package...
        run: pkg/release-deb.sh
      - name: Archiving deb package...
        run: 7z a kime-deb.7z ./build/deb/*

      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/kime.7z
          asset_name: kime-${{ github.ref }}.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/kime-deb.7z
          asset_name: kime-dev-${{ github.ref }}.7z
          asset_content_type: application/x-7z-compressed
  
